### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Flakebi** [Splamy/TravisExperiments#1]
This doesn’t work for me.
How can I use this?

**Comment by Flakebi** [comment]
Ah, got it working now

**Comment by Flakebi** [comment]
Ping @Splamy

**Comment by Splamy** [comment]
Uhm kay

**Comment by Splamy** [comment]
Here's the demo: https://gist.github.com/Splamy/3d910e71684ef5b9964e46833a7de709
